version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/infra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/bootstrap"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/demo-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/demo-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
