apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-demo
  namespace: platform-demo
  labels:
    app.kubernetes.io/name: platform-demo
    app.kubernetes.io/part-of: platform-engineering-lab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
