apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://opencost.github.io/opencost-helm-chart
      chart: opencost
      targetRevision: 2.5.31
      helm:
        valueFiles:
          - $values/cost/opencost-values.yaml
    - repoURL: https://github.com/fadyy2k/platform-engineering-eks-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
